//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CAAPDATA_MNL_DbSet : DbContext
    {
        public CAAPDATA_MNL_DbSet()
            : base("name=CAAPDATA_MNL_DbSet")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAirman> tblAirmen { get; set; }
        public virtual DbSet<tblAMType> tblAMTypes { get; set; }
        public virtual DbSet<tblAnswerSheet1> tblAnswerSheet1 { get; set; }
        public virtual DbSet<tblAnswerSheet2> tblAnswerSheet2 { get; set; }
        public virtual DbSet<tblApplication> tblApplications { get; set; }
        public virtual DbSet<tblLicType1> tblLicType1 { get; set; }
        public virtual DbSet<tblLicType2> tblLicType2 { get; set; }
        public virtual DbSet<tblNationality> tblNationalities { get; set; }
        public virtual DbSet<tblQuestionnaire> tblQuestionnaires { get; set; }
        public virtual DbSet<tblSchool> tblSchools { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblTestReportApplication> tblTestReportApplications { get; set; }
    
        public virtual ObjectResult<getAirmenAll> getAirmen_all(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAirmenAll>("getAirmen_all", searchParameter);
        }
    
        public virtual ObjectResult<ExamHistoryResult> ExamHistory(string pEL, Nullable<int> aM_Type)
        {
            var pELParameter = pEL != null ?
                new ObjectParameter("PEL", pEL) :
                new ObjectParameter("PEL", typeof(string));
    
            var aM_TypeParameter = aM_Type.HasValue ?
                new ObjectParameter("AM_Type", aM_Type) :
                new ObjectParameter("AM_Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ExamHistoryResult>("ExamHistory", pELParameter, aM_TypeParameter);
        }
    
        public virtual int trInitial(string pEL, Nullable<int> amType, string initial, Nullable<System.DateTime> iDate, string remarks)
        {
            var pELParameter = pEL != null ?
                new ObjectParameter("PEL", pEL) :
                new ObjectParameter("PEL", typeof(string));
    
            var amTypeParameter = amType.HasValue ?
                new ObjectParameter("amType", amType) :
                new ObjectParameter("amType", typeof(int));
    
            var initialParameter = initial != null ?
                new ObjectParameter("Initial", initial) :
                new ObjectParameter("Initial", typeof(string));
    
            var iDateParameter = iDate.HasValue ?
                new ObjectParameter("iDate", iDate) :
                new ObjectParameter("iDate", typeof(System.DateTime));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("trInitial", pELParameter, amTypeParameter, initialParameter, iDateParameter, remarksParameter);
        }
    
        public virtual ObjectResult<viewTRApplication> viewTRApplication(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTRApplication>("viewTRApplication", searchParameter);
        }
    
        public virtual int trBatchUpdate(string status, string batchNo, string lastModifiedBy, Nullable<System.DateTime> pendingDate, Nullable<System.DateTime> recievedDate)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var batchNoParameter = batchNo != null ?
                new ObjectParameter("BatchNo", batchNo) :
                new ObjectParameter("BatchNo", typeof(string));
    
            var lastModifiedByParameter = lastModifiedBy != null ?
                new ObjectParameter("LastModifiedBy", lastModifiedBy) :
                new ObjectParameter("LastModifiedBy", typeof(string));
    
            var pendingDateParameter = pendingDate.HasValue ?
                new ObjectParameter("PendingDate", pendingDate) :
                new ObjectParameter("PendingDate", typeof(System.DateTime));
    
            var recievedDateParameter = recievedDate.HasValue ?
                new ObjectParameter("RecievedDate", recievedDate) :
                new ObjectParameter("RecievedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("trBatchUpdate", statusParameter, batchNoParameter, lastModifiedByParameter, pendingDateParameter, recievedDateParameter);
        }
    
        public virtual int trTagAsPending(string status, string batchNo, string lastModifiedBy, Nullable<System.DateTime> pendingDate)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var batchNoParameter = batchNo != null ?
                new ObjectParameter("BatchNo", batchNo) :
                new ObjectParameter("BatchNo", typeof(string));
    
            var lastModifiedByParameter = lastModifiedBy != null ?
                new ObjectParameter("LastModifiedBy", lastModifiedBy) :
                new ObjectParameter("LastModifiedBy", typeof(string));
    
            var pendingDateParameter = pendingDate.HasValue ?
                new ObjectParameter("PendingDate", pendingDate) :
                new ObjectParameter("PendingDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("trTagAsPending", statusParameter, batchNoParameter, lastModifiedByParameter, pendingDateParameter);
        }
    
        public virtual int trTagAsRecieved(string status, string batchNo, string lastModifiedBy, Nullable<System.DateTime> recievedDate)
        {
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var batchNoParameter = batchNo != null ?
                new ObjectParameter("BatchNo", batchNo) :
                new ObjectParameter("BatchNo", typeof(string));
    
            var lastModifiedByParameter = lastModifiedBy != null ?
                new ObjectParameter("LastModifiedBy", lastModifiedBy) :
                new ObjectParameter("LastModifiedBy", typeof(string));
    
            var recievedDateParameter = recievedDate.HasValue ?
                new ObjectParameter("RecievedDate", recievedDate) :
                new ObjectParameter("RecievedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("trTagAsRecieved", statusParameter, batchNoParameter, lastModifiedByParameter, recievedDateParameter);
        }
    }
}
