//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAAPDATA_NLA_DbSet : DbContext
    {
        public CAAPDATA_NLA_DbSet()
            : base("name=CAAPDATA_NLA_DbSet")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAirman> tblAirmen { get; set; }
        public virtual DbSet<tblAMType> tblAMTypes { get; set; }
        public virtual DbSet<tblAnswerSheet1> tblAnswerSheet1 { get; set; }
        public virtual DbSet<tblAnswerSheet2> tblAnswerSheet2 { get; set; }
        public virtual DbSet<tblApplication> tblApplications { get; set; }
        public virtual DbSet<tblLicType1> tblLicType1 { get; set; }
        public virtual DbSet<tblLicType2> tblLicType2 { get; set; }
        public virtual DbSet<tblNationality> tblNationalities { get; set; }
        public virtual DbSet<tblQuestionnaire> tblQuestionnaires { get; set; }
        public virtual DbSet<tblSchool> tblSchools { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
