//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    
    public partial class ExamHistoryResult
    {
        public string airmen_name { get; set; }
        public string Subject { get; set; }
        public string PassFail { get; set; }
        public double Rating { get; set; }
        public string exam_date { get; set; }
        public int Applicant_id { get; set; }
        public int Correct_Ans { get; set; }
        public int No_Items { get; set; }
        public string Loc { get; set; }
        public int Subject_ID { get; set; }
        public string License { get; set; }
        public string PEL { get; set; }
    }
}
