//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    
    public partial class getAirmenAll
    {
        public Nullable<int> recid { get; set; }
        public string PEL { get; set; }
        public string Fullname { get; set; }
        public Nullable<int> AirmenType { get; set; }
        public string Airmen_Desc { get; set; }
        public string Loc { get; set; }
    }
}
