//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnswerSheet1
    {
        public int exam_id { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public Nullable<int> am_type { get; set; }
        public Nullable<int> Applicant_id { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<int> Correct_Ans { get; set; }
        public Nullable<int> No_Items { get; set; }
        public Nullable<int> Sched_time { get; set; }
        public Nullable<int> PassWD { get; set; }
        public string control_no { get; set; }
        public Nullable<System.DateTime> log_time { get; set; }
        public Nullable<int> TimeLeft { get; set; }
    }
}
