//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnswerSheet2
    {
        public Nullable<int> exam_id { get; set; }
        public int Line_no { get; set; }
        public Nullable<int> Question_id { get; set; }
        public string E_answer { get; set; }
        public string C_Answer { get; set; }
        public Nullable<int> Skip_Level { get; set; }
    }
}
