//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLicType2
    {
        public Nullable<int> Code { get; set; }
        public int Line_no { get; set; }
        public string Subject { get; set; }
        public Nullable<int> no_of_items { get; set; }
        public string Remarks { get; set; }
        public string exam_day { get; set; }
        public string exam_time { get; set; }
    }
}
