//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionnaire
    {
        public int Question_Id { get; set; }
        public Nullable<int> Batch_no { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public string Question { get; set; }
        public string A_answer { get; set; }
        public string B_answer { get; set; }
        public string C_answer { get; set; }
        public string D_answer { get; set; }
        public string Correct_answer { get; set; }
    }
}
