//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestReportApplication
    {
        public int Id { get; set; }
        public string PEL { get; set; }
        public int amType { get; set; }
        public string Status { get; set; }
        public string Initial { get; set; }
        public System.DateTime iDate { get; set; }
        public string ControlledBy { get; set; }
        public string ControlNo { get; set; }
        public System.DateTime cDate { get; set; }
        public string ReleasedBy { get; set; }
        public System.DateTime rDate { get; set; }
        public string Remarks { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime pDate { get; set; }
        public System.DateTime Received { get; set; }
    }
}
