//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEBSystem.Core.Models
{
    using System;
    
    public partial class viewTRApplication
    {
        public int Id { get; set; }
        public string PEL { get; set; }
        public Nullable<int> amType { get; set; }
        public string Status { get; set; }
        public string Initial { get; set; }
        public Nullable<System.DateTime> iDate { get; set; }
        public string ControlledBy { get; set; }
        public string ControlNo { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public string ReleasedBy { get; set; }
        public Nullable<System.DateTime> rDate { get; set; }
        public string Remarks { get; set; }
        public string LastModifiedBy { get; set; }
        public string Fullname { get; set; }
        public string License_Type { get; set; }
    }
}
